apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: devops-microshop
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: devops-microshop
  endpoints:
    - port: http
      path: /metrics
      interval: 15s


