name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
      - name: Install and build
        working-directory: app
        run: |
          npm ci
          npm run start --if-present
      - name: Lint placeholder
        run: echo "No lint configured"


